=== SeequentEvo/evo-schemas/schema/components/geometry-part/1.0.2/geometry-part.schema.json
{
  "$id": "/components/geometry-part/1.0.2/geometry-part.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "This component describes a geometry part.",
  "type": "object",
  "properties": {
    "key": {
      "type": "string",
      "description": "Unique identifier of the geometry part."
    },
    "name": {
      "type": "string",
      "description": "Name."
    },
    "data_source": {
      "type": "string",
      "description": "Data source."
    },
    "feature": {
      "title": "Geometry part feature",
      "type": "object",
      "description": "Geometry part feature.",
      "properties": {
        "name": {
          "type": "string",
          "description": "Feature name."
        },
        "kind": {
          "type": "string",
          "description": "Kind of feature.",
          "enum": [
            "Void",
            "Soil",
            "GMV",
            "Discontinuity",
            "Plate",
            "Geogrid",
            "Beam",
            "EmbeddedBeam",
            "Cable",
            "Anchor"
          ]
        },
        "material_key": {
          "type": "string",
          "description": "Unique identifier of the material."
        }
      },
      "required": [
        "name",
        "kind"
      ]
    },
    "transform": {
      "title": "Transformation matrix",
      "type": "array",
      "description": "4x4 transformation matrix flattened in row-major order.",
      "maxItems": 16,
      "minItems": 16,
      "items": {
        "type": "number"
      }
    },
    "bounding_box": {
      "title": "Bounding box",
      "description": "Bounding box of the geometry part.",
      "$ref": "/components/bounding-box/1.0.2/bounding-box.schema.json"
    },
    "layer": {
      "type": "string",
      "description": "Geometry part layer."
    },
    "color": {
      "description": "Geometry part color.",
      "$ref": "/elements/color/1.0.1/color.schema.json"
    },
    "geometry": {
      "description": "Another part in the geometry or a geometry composite.",
      "oneOf": [
        {
          "type": "object",
          "description": "Another part in the geometry",
          "properties": {
            "part_key": {
              "type": "string",
              "description": "Unique identifier of another part in the geometry."
            }
          },
          "required": [
            "part_key"
          ]
        },
        {
          "description": "Geometry composite.",
          "$ref": "/components/geometry-composite/1.0.1/geometry-composite.schema.json"
        }
      ]
    }
  },
  "required": [
    "key",
    "name",
    "feature",
    "bounding_box",
    "geometry"
  ]
}

=== SeequentEvo/evo-schemas/examples/1.0.2/components/geometry-part-2.json
{
  "$schema": "/components/geometry-part/1.0.2/geometry-part.schema.json",
  "key": "part 1",
  "name": "geometry part 1",
  "data_source": "https://mycompany/mesh11.stl",
  "feature": {
    "name": "feature 1",
    "kind": "Soil",
    "material_key": "soil"
  },
  "transform": [
    1.0,
    0.0,
    0.0,
    45.0,
    0.0,
    1.0,
    0.0,
    45.0,
    0.0,
    0.0,
    1.0,
    30.0,
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "bounding_box": {
    "min_y": 5,
    "max_y": 10,
    "min_x": 0,
    "max_x": 10,
    "min_z": 5,
    "max_z": 10
  },
  "geometry": {
    "brep_container": {
      "format": "STEP",
      "producer": "Plaxis",
      "brep": {
        "width": 1,
        "data_type": "uint8",
        "length": 2000,
        "data": "abababababababababababababababababababababababababababababababab"
      }
    },
    "mesh": {
      "kind": "Open",
      "quality": {
        "characteristics": [
          "NonSelfIntersecting",
          "Continuous"
        ]
      },
      "triangles": {
        "width": 3,
        "data_type": "uint64",
        "length": 4,
        "data": "abababababababababababababababababababababababababababababababab"
      }
    },
    "points_2d": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ],
    "polylines_2d": [
      {
        "begin": 1,
        "count": 3,
        "closed": "Closed",
        "shape": "Straight"
      },
      {
        "begin": 7,
        "count": 3,
        "closed": "Closed",
        "shape": "Curved"
      }
    ],
    "points_3d": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ],
    "polylines_3d": [
      {
        "begin": 1,
        "count": 2,
        "closed": "Closed"
      },
      {
        "begin": 5,
        "count": 3,
        "closed": "Open"
      }
    ]
  }
}

=== SeequentEvo/evo-schemas/examples/1.0.2/components/geometry-part-1.json
{
  "$schema": "/components/geometry-part/1.0.2/geometry-part.schema.json",
  "key": "part 1",
  "name": "geometry part 1",
  "data_source": "https://mycompany/mesh11.stl",
  "feature": {
    "name": "feature 1",
    "kind": "Soil",
    "material_key": "soil"
  },
  "transform": [
    1.0,
    0.0,
    0.0,
    45.0,
    0.0,
    1.0,
    0.0,
    45.0,
    0.0,
    0.0,
    1.0,
    30.0,
    0.0,
    0.0,
    0.0,
    1.0
  ],
  "bounding_box": {
    "min_y": 5,
    "max_y": 10,
    "min_x": 0,
    "max_x": 10,
    "min_z": 5,
    "max_z": 10
  },
  "geometry": {
    "part_key": "part 2"
  }
}
